import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Activity, Database, DollarSign, TrendingUp, Upload, Users } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatCard } from "@/components/ui/StatCard";
import { platformApi } from "@/api/platform";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
export const Route = createFileRoute("/_app/home")({ component: HomePage });
function HomePage() { const dashboard = useQuery({ queryKey:["dashboard"], queryFn: platformApi.dashboard }); const me = useQuery({queryKey:["current-user"],queryFn:platformApi.me}); const activity = useQuery({queryKey:["activity"], queryFn:platformApi.activity}); const d = dashboard.data; const trend = (d?.revenue_trend ?? []).map((x:{period:string;revenue:number})=>({d:x.period,v:x.revenue}));
return <div className="space-y-6"><section className="rounded-3xl border p-8"><h1 className="text-3xl font-bold">Welcome back, {me.data?.name ?? me.data?.email ?? ""}</h1><p className="mt-2 text-muted-foreground">Your uploaded data is powering this live workspace.</p><Link to="/upload"><Button className="mt-4"><Upload className="mr-2 h-4 w-4"/>Upload dataset</Button></Link></section><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Customers" value={Number(d?.total_customers ?? 0).toLocaleString()} delta="Live" trend="up" icon={Users} data={trend.map((x:{v:number})=>x.v)}/><StatCard label="Revenue" value={`$${Number(d?.revenue ?? 0).toLocaleString()}`} delta="Live" trend="up" icon={DollarSign} data={trend.map((x:{v:number})=>x.v)}/><StatCard label="Transactions" value={Number(d?.transactions ?? 0).toLocaleString()} delta="Live" trend="up" icon={Activity} data={trend.map((x:{v:number})=>x.v)}/><StatCard label="Datasets" value={Number(d?.datasets ?? 0).toLocaleString()} delta="Live" trend="up" icon={Database} data={trend.map((x:{v:number})=>x.v)}/></div><div className="grid gap-4 lg:grid-cols-3"><Card className="p-6 lg:col-span-2"><h3 className="font-semibold">Revenue trend</h3><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><XAxis dataKey="d"/><YAxis/><Tooltip/><Area dataKey="v" stroke="var(--brand)" fill="var(--brand)" fillOpacity={.25}/></AreaChart></ResponsiveContainer></div></Card><Card className="p-6"><h3 className="font-semibold">Recent activity</h3><ul className="mt-3 space-y-3 text-sm">{(activity.data ?? []).map((a:{who:string;what:string;when:string}, i:number)=><li key={i}><b>{a.who}</b> {a.what}<div className="text-xs text-muted-foreground">{a.when}</div></li>)}</ul></Card></div></div>; }
